version: '3.4'
services:
  angular-app:
    image: angular-app
    build: 
      context: ./angular-app
      dockerfile: ./angular-app/Dockerfile 
    ports:
      - 80:80
    links: 
     - node-app
  node-app: 
    container_name: node-app-service
    restart: always
    build:
      context: ./node-app
      dockerfile: ./node-app/Dockerfile
    ports:
      - '3000:3000'
    links: 
      - mongo
  mongo:
    container_name: mongo-app-service
    image: mongo
    ports:
      - '27017:27017'      